//! BATS script transpiler
//!
//! Transforms Gherkin AST into native BATS bash scripts.

use crate::parser::ast::{Feature, Scenario, SimpleScenario, ScenarioOutline, Step, Background};

use thiserror::Error;

/// Compile-time errors
#[derive(Error, Debug)]
pub enum CompileError {
    #[error("Placeholder '{0}' not found in examples table")]
    PlaceholderNotFound(String),
}

/// Transpile a Gherkin feature to BATS bash script
pub fn transpile_to_bats(feature: &Feature) -> Result<String, CompileError> {
    let mut output = String::new();

    // Header
    output.push_str("#!/usr/bin/env bats\n");
    output.push_str(&format!("# Auto-generated by BATS-BDD from: {}.feature\n\n",
        feature.name.replace(' ', "_").to_lowercase()));

    // Load step definitions
    output.push_str("load 'step_definitions.bash'\n\n");
    // Feature tags as comments
    if !feature.tags.is_empty() {
        output.push_str(&format!("# Feature tags: {}\n", feature.tags.join(", ")));
    }

    // Background → setup()
    if let Some(background) = &feature.background {
        output.push_str(&transpile_background(background));
        output.push_str("\n");
    }

    // Scenarios → @test blocks
    for scenario in &feature.scenarios {
        match scenario {
            Scenario::Simple(simple) => {
                output.push_str(&transpile_simple_scenario(simple));
                output.push_str("\n");
            }
            Scenario::Outline(outline) => {
                output.push_str(&transpile_scenario_outline(outline)?);
                output.push_str("\n");
            }
        }
    }

    Ok(output)
}

/// Transpile Background to setup() function
fn transpile_background(background: &Background) -> String {
    let mut output = String::new();
    output.push_str("setup() {\n");
    
    for step in &background.steps {
        let func_name = step_to_func_name(step);
        output.push_str(&format!("  {}\n", func_name));
    }
    
    output.push_str("}\n");
    output
}

/// Transpile a simple scenario to @test block
fn transpile_simple_scenario(scenario: &SimpleScenario) -> String {
    let mut output = String::new();
    let test_name = scenario.name.replace('"', "\\\"");
    
    // Scenario tags as comments
    if !scenario.tags.is_empty() {
        output.push_str(&format!("# Tags: {}\n", scenario.tags.join(", ")));
    }

    output.push_str(&format!("@test \"{}\" {{\n", test_name));
    
    for step in &scenario.steps {
        let func_name = step_to_func_name(step);
        output.push_str(&format!("  {}\n", func_name));
    }
    
    output.push_str("}\n");
    output
}

/// Transpile a scenario outline to multiple @test blocks (one per example row)
fn transpile_scenario_outline(outline: &ScenarioOutline) -> Result<String, CompileError> {
    let mut output = String::new();
    let headers = &outline.examples.table.rows[0];

    // Generate one @test per example row
    for (row_idx, row) in outline.examples.table.rows.iter().skip(1).enumerate() {
        let test_name = format!("{} [Example {}]", outline.name.replace('"', "\\\""), row_idx + 1);
        output.push_str(&format!("@test \"{}\" {{\n", test_name));

        for step in &outline.steps {
            let (func_name, args) = step_to_func_call(step, headers, row)?;
            let call = if args.is_empty() {
                func_name
            } else {
                format!("{} {}", func_name, args.join(" "))
            };
            output.push_str(&format!("  {}\n", call));
        }

        output.push_str("}\n");
    }

    Ok(output)
}

/// Convert a step to a function call with arguments
/// For outlines: extracts placeholders, generates canonical function name, returns arguments
fn step_to_func_call(step: &Step, headers: &[String], row: &[String]) -> Result<(String, Vec<String>), CompileError> {
    let keyword = step.keyword().to_lowercase();
    let text = step.text();

    // Find all placeholders in the text and their positions
    let placeholders = extract_placeholders(text);

    // Build canonical text: replace <placeholder> with placeholder name
    let mut canonical_text = text.to_string();
    for (placeholder, name) in &placeholders {
        canonical_text = canonical_text.replace(placeholder, name);
    }

    // Generate function name from canonical text
    let func_name = format!("step_{}_{}", keyword, to_snake_case(&canonical_text));

    // Build arguments: look up each placeholder value in row using header index
    let mut args = Vec::new();
    for (_, name) in &placeholders {
        if let Some(idx) = headers.iter().position(|h| h == name) {
            if idx < row.len() {
                args.push(quote_bash_arg(&row[idx]));
            }
        } else {
            return Err(CompileError::PlaceholderNotFound(name.clone()));
        }
    }

    Ok((func_name, args))
}

/// Extract placeholders like <name> from text, returning (full_placeholder, name)
fn extract_placeholders(text: &str) -> Vec<(String, String)> {
    let mut placeholders = Vec::new();
    let mut chars = text.chars().peekable();
    
    while let Some(ch) = chars.next() {
        if ch == '<' {
            let mut name = String::new();
            while let Some(inner_ch) = chars.next() {
                if inner_ch == '>' {
                    if !name.is_empty() {
                        placeholders.push((format!("<{}>", name), name.clone()));
                    }
                    break;
                } else {
                    name.push(inner_ch);
                }
            }
        }
    }
    
    placeholders
}

/// Convert text to snake_case for function names
fn to_snake_case(text: &str) -> String {
    text
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == ' ' {
                c
            } else {
                '_'
            }
        })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<&str>>()
        .join("_")
        .to_lowercase()
}

/// Quote a string for safe use as a bash argument
fn quote_bash_arg(arg: &str) -> String {
    // If arg contains spaces, quotes, or other special chars, wrap in double quotes
    if arg.chars().any(|c| c.is_whitespace() || c == '"' || c == '\'' || c == '$' || c == '`') {
        // Escape double quotes and backslashes
        let escaped = arg.replace('\\', "\\\\").replace('"', "\\\"");
        format!("\"{}\"", escaped)
    } else {
        // Safe to use unquoted
        arg.to_string()
    }
}



/// Convert a step to a bash function name
/// Example: "Given I run the command `ls`" → "step_given_i_run_the_command_ls"
pub fn step_to_func_name(step: &Step) -> String {
    let keyword = step.keyword().to_lowercase();
    let func_text = to_snake_case(step.text());
    format!("step_{}_{}", keyword, func_text)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_step_to_func_name_simple() {
        let step = Step::Given("I have a calculator".to_string(), None, None);
        assert_eq!(step_to_func_name(&step), "step_given_i_have_a_calculator");
    }
    
    #[test]
    fn test_step_to_func_name_with_backticks() {
        let step = Step::Given("I run the command `ls`".to_string(), None, None);
        assert_eq!(step_to_func_name(&step), "step_given_i_run_the_command__ls_");
    }
    
    #[test]
    fn test_step_to_func_name_with_quotes() {
        let step = Step::Then("the result should be \"5\"".to_string(), None, None);
        assert_eq!(step_to_func_name(&step), "step_then_the_result_should_be__5_");
    }
    
    #[test]
    fn test_extract_placeholders() {
        let text = "I add <a> and <b>";
        let placeholders = extract_placeholders(text);
        assert_eq!(placeholders, vec![("<a>".to_string(), "a".to_string()), ("<b>".to_string(), "b".to_string())]);
    }
    
    #[test]
    fn test_extract_placeholders_none() {
        let text = "I have a calculator";
        let placeholders = extract_placeholders(text);
        assert!(placeholders.is_empty());
    }
    
    #[test]
    fn test_step_to_func_call_with_placeholders() {
        let step = Step::When("I add <a> and <b>".to_string(), None, None);
        let headers = vec!["a".to_string(), "b".to_string()];
        let row = vec!["1".to_string(), "2".to_string()];
        let (func_name, args) = step_to_func_call(&step, &headers, &row).unwrap();
        assert_eq!(func_name, "step_when_i_add_a_and_b");
        assert_eq!(args, vec!["1", "2"]);
    }
    
    #[test]
    fn test_step_to_func_call_no_placeholders() {
        let step = Step::Given("I have a calculator".to_string(), None, None);
        let headers: Vec<String> = vec![];
        let row: Vec<String> = vec![];
        let (func_name, args) = step_to_func_call(&step, &headers, &row).unwrap();
        assert_eq!(func_name, "step_given_i_have_a_calculator");
        assert!(args.is_empty());
    }
    
    #[test]
    fn test_step_to_func_call_quoted_args() {
        let step = Step::Given("I have the string <input>".to_string(), None, None);
        let headers = vec!["input".to_string()];
        let row = vec!["hello world".to_string()];
        let (func_name, args) = step_to_func_call(&step, &headers, &row).unwrap();
        assert_eq!(func_name, "step_given_i_have_the_string_input");
        assert_eq!(args, vec!["\"hello world\""]);
    }

    #[test]
    fn test_step_to_func_call_placeholder_not_found() {
        let step = Step::When("I add <banana>".to_string(), None, None);
        let headers = vec!["a".to_string(), "b".to_string()];
        let row = vec!["1".to_string(), "2".to_string()];
        let result = step_to_func_call(&step, &headers, &row);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(matches!(err, CompileError::PlaceholderNotFound(_)));
        assert_eq!(err.to_string(), "Placeholder 'banana' not found in examples table");
    }
    
    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("Hello World"), "hello_world");
        assert_eq!(to_snake_case("Test 123"), "test_123");
        assert_eq!(to_snake_case("Special!@#Chars"), "special___chars");
    }
    
    #[test]
    fn test_quote_bash_arg() {
        assert_eq!(quote_bash_arg("simple"), "simple");
        assert_eq!(quote_bash_arg("hello world"), "\"hello world\"");
        assert_eq!(quote_bash_arg("test\"quote"), "\"test\\\"quote\"");
    }
}
