//! BATS script transpiler
//!
//! Transforms Gherkin AST into native BATS bash scripts.

use crate::parser::ast::{Background, Feature, Scenario, ScenarioOutline, SimpleScenario, Step};

use thiserror::Error;

/// Compile-time errors
#[derive(Error, Debug)]
pub enum CompileError {
    #[error("Placeholder '{0}' not found in examples table")]
    PlaceholderNotFound(String),
    #[error("Examples table cannot be empty")]
    EmptyExamplesTable,
}

/// Transpile a Gherkin feature to BATS bash script
/// Transpile a Gherkin feature to BATS bash script
pub fn transpile_to_bats(feature: &Feature, steps_file: &str) -> Result<String, CompileError> {
    let mut output = String::new();

    // Header
    output.push_str("#!/usr/bin/env bats\n");
    output.push_str(&format!(
        "# Auto-generated by BATS-BDD from: {}.feature\n\n",
        feature.name.replace(' ', "_").to_lowercase()
    ));

    // Load step definitions
    output.push_str(&format!("load '{}'\n\n", steps_file));
    // Feature tags as comments
    if !feature.tags.is_empty() {
        output.push_str(&format!("# Feature tags: {}\n", feature.tags.join(", ")));
    }

    // Background → setup()
    if let Some(background) = &feature.background {
        output.push_str(&transpile_background(background));
        output.push('\n');
    }

    // Scenarios → @test blocks
    for scenario in &feature.scenarios {
        match scenario {
            Scenario::Simple(simple) => {
                output.push_str(&transpile_simple_scenario(simple));
                output.push('\n');
            }
            Scenario::Outline(outline) => {
                output.push_str(&transpile_scenario_outline(outline)?);
                output.push('\n');
            }
        }
    }
    // Rules (Gherkin 6+) → @test blocks
    for rule in &feature.rules {
        output.push_str(&format!("\n# Rule: {}\n", rule.name));

        // Rule tags as comments
        if !rule.tags.is_empty() {
            output.push_str(&format!("# Rule tags: {}\n", rule.tags.join(", ")));
        }

        // Process rule background if present
        let rule_background = &rule.background;

        for scenario in &rule.scenarios {
            match scenario {
                Scenario::Simple(simple) => {
                    // Use background-aware transpilation if rule background present
                    if let Some(bg) = rule_background {
                        output.push_str(&transpile_simple_scenario_with_background(simple, bg));
                    } else {
                        output.push_str(&transpile_simple_scenario(simple));
                    }
                    output.push('\n');
                }
                Scenario::Outline(outline) => {
                    // Inject rule background steps before outline steps if present
                    if let Some(bg) = rule_background {
                        output.push_str(&transpile_scenario_outline_with_background(outline, bg)?);
                    } else {
                        output.push_str(&transpile_scenario_outline(outline)?);
                    }
                    output.push('\n');
                }
            }
        }
    }

    Ok(output)
}

/// Transpile Background to setup() function
fn transpile_background(background: &Background) -> String {
    let mut output = String::new();
    output.push_str("setup() {\n");

    for step in &background.steps {
        output.push_str(&step_to_bash_call(step));
    }
    output.push_str("}\n");
    output
}

/// Transpile a simple scenario to @test block
fn transpile_simple_scenario(scenario: &SimpleScenario) -> String {
    let mut output = String::new();
    let test_name = scenario.name.replace('\\', "\\\\").replace('\'', "'\\\\'");

    // Scenario tags as comments
    if !scenario.tags.is_empty() {
        output.push_str(&format!("# Tags: {}\n", scenario.tags.join(", ")));
    }

    output.push_str(&format!("@test '{}' {{\n", test_name));

    for step in &scenario.steps {
        output.push_str(&step_to_bash_call(step));
    }
    output.push_str("}\n");
    output
}

/// Transpile a simple scenario with rule background injected inside the @test block
fn transpile_simple_scenario_with_background(
    scenario: &SimpleScenario,
    background: &Background,
) -> String {
    let mut output = String::new();
    let test_name = scenario.name.replace('\\', "\\\\").replace('\'', "'\\\\'");

    // Scenario tags as comments
    if !scenario.tags.is_empty() {
        output.push_str(&format!("# Tags: {}\n", scenario.tags.join(", ")));
    }

    output.push_str(&format!("@test '{}' {{\n", test_name));

    // Inject background steps inside the @test block
    output.push_str("# Rule Background\n");
    for step in &background.steps {
        output.push_str(&step_to_bash_call(step));
    }

    for step in &scenario.steps {
        output.push_str(&step_to_bash_call(step));
    }
    output.push_str("}\n");
    output
}

/// Transpile a scenario outline to multiple @test blocks (one per example row)
fn transpile_scenario_outline(outline: &ScenarioOutline) -> Result<String, CompileError> {
    let mut output = String::new();

    // Validate examples table has at least a header row
    if outline.examples.table.rows.is_empty() {
        return Err(CompileError::EmptyExamplesTable);
    }
    let headers = &outline.examples.table.rows[0];

    // Generate one @test per example row
    for (row_idx, row) in outline.examples.table.rows.iter().skip(1).enumerate() {
        // Escape $ and backticks for single-quoted test names
        let escaped_name = outline.name.replace('\\', "\\\\").replace('\'', "'\\\\'");
        let test_name = format!("{} [Example {}]", escaped_name, row_idx + 1);
        output.push_str(&format!("@test '{}' {{\n", test_name));

        for step in &outline.steps {
            let step_call = step_to_bash_call_with_args(step, headers, row)?;
            output.push_str(&step_call);
        }

        output.push_str("}\n");
    }

    Ok(output)
}

/// Transpile a scenario outline with rule background injected before each test
fn transpile_scenario_outline_with_background(
    outline: &ScenarioOutline,
    background: &Background,
) -> Result<String, CompileError> {
    let mut output = String::new();

    // Validate examples table has at least a header row
    if outline.examples.table.rows.is_empty() {
        return Err(CompileError::EmptyExamplesTable);
    }
    let headers = &outline.examples.table.rows[0];

    // Generate one @test per example row
    for (row_idx, row) in outline.examples.table.rows.iter().skip(1).enumerate() {
        // Escape $ and backticks for single-quoted test names
        let escaped_name = outline.name.replace('\\', "\\\\").replace('\'', "'\\\\'");
        let test_name = format!("{} [Example {}]", escaped_name, row_idx + 1);
        output.push_str(&format!("@test '{}' {{\n", test_name));

        // Inject background steps before scenario steps
        output.push_str("# Rule Background\n");
        for step in &background.steps {
            // Background steps in outlines don't have table placeholders,
            // so we use the regular step_to_bash_call
            output.push_str(&step_to_bash_call(step));
        }

        // Process scenario outline steps with example substitution
        for step in &outline.steps {
            let step_call = step_to_bash_call_with_args(step, headers, row)?;
            output.push_str(&step_call);
        }

        output.push_str("}\n");
    }

    Ok(output)
}
/// Convert a step to a function call with arguments
/// For outlines: extracts placeholders, generates canonical function name, returns arguments
fn step_to_func_call(
    step: &Step,
    headers: &[String],
    row: &[String],
) -> Result<(String, Vec<String>), CompileError> {
    let keyword = step.keyword().to_lowercase();
    let text = step.text();

    // Find all placeholders in the text and their positions
    let placeholders = extract_placeholders(text);

    // Build canonical text: replace <placeholder> with placeholder name
    let mut canonical_text = text.to_string();
    for (placeholder, name) in &placeholders {
        canonical_text = canonical_text.replace(placeholder, name);
    }

    // Generate function name from canonical text
    let func_name = format!("step_{}_{}", keyword, to_snake_case(&canonical_text));

    // Build arguments: look up each placeholder value in row using header index
    let mut args = Vec::new();
    for (_, name) in &placeholders {
        if let Some(idx) = headers.iter().position(|h| h == name) {
            if idx < row.len() {
                args.push(quote_bash_arg(&row[idx]));
            } else {
                return Err(CompileError::PlaceholderNotFound(format!(
                    "{} (row has {} columns but header has {})",
                    name,
                    row.len(),
                    headers.len()
                )));
            }
        } else {
            return Err(CompileError::PlaceholderNotFound(name.clone()));
        }
    }

    Ok((func_name, args))
}

/// Extract placeholders like <name> from text, returning (full_placeholder, name)
/// Only matches valid identifiers: <[A-Za-z0-9_]+>
fn extract_placeholders(text: &str) -> Vec<(String, String)> {
    let mut placeholders = Vec::new();
    let mut chars = text.chars().peekable();

    while let Some(ch) = chars.next() {
        if ch == '<' {
            let mut name = String::new();
            #[allow(clippy::while_let_on_iterator)]
            while let Some(inner_ch) = chars.peek() {
                if *inner_ch == '>' {
                    // End of placeholder
                    chars.next(); // consume '>'
                                  // Only accept if name is non-empty and contains valid identifier chars
                    if !name.is_empty() && name.chars().all(|c| c.is_alphanumeric() || c == '_') {
                        placeholders.push((format!("<{}>", name), name.clone()));
                    }
                    break;
                } else if inner_ch.is_alphanumeric() || *inner_ch == '_' {
                    name.push(*inner_ch);
                    chars.next(); // consume valid char
                } else {
                    // Invalid character - skip until we find '>' or end
                    chars.next(); // skip invalid char
                                  // Continue until we find '>' or end
                    while let Some(skip_ch) = chars.peek() {
                        if *skip_ch == '>' {
                            break;
                        }
                        chars.next();
                    }
                    break;
                }
            }
        }
    }

    placeholders
}

/// Convert text to snake_case for function names
/// Handles Unicode characters by decomposing and removing diacritics
fn to_snake_case(text: &str) -> String {
    // Normalize Unicode: decompose characters (e.g., á → a)
    // then filter out diacritics and convert to ASCII equivalents
    let normalized: String = text
        .chars()
        .flat_map(|c| {
            // First, try to decompose any diacritics
            let decomposed = decompose_diacritic(c);
            // If character changed (had diacritic), use the decomposed version
            if decomposed != c {
                vec![decomposed]
            } else if c.is_alphanumeric() {
                vec![c]
            } else if c.is_whitespace() {
                vec![' ']
            } else {
                vec!['_'] // Unknown/special character
            }
        })
        .collect();

    normalized
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == ' ' {
                c
            } else {
                '_'
            }
        })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<&str>>()
        .join("_")
        .to_lowercase()
}

/// Decompose a character by removing common diacritics
fn decompose_diacritic(c: char) -> char {
    match c {
        // Lowercase with accent
        'à' | 'á' | 'â' | 'ã' | 'ä' | 'å' | 'ā' | 'ă' | 'ą' => 'a',
        'è' | 'é' | 'ê' | 'ë' | 'ē' | 'ĕ' | 'ė' | 'ę' | 'ě' => 'e',
        'ì' | 'í' | 'î' | 'ï' | 'ī' | 'ĭ' | 'į' | 'ı' => 'i',
        'ò' | 'ó' | 'ô' | 'õ' | 'ö' | 'ø' | 'ō' | 'ŏ' | 'ő' | 'œ' => 'o',
        'ù' | 'ú' | 'û' | 'ü' | 'ū' | 'ŭ' | 'ů' | 'ų' | 'ű' => 'u',
        'ý' | 'ÿ' | 'ȳ' => 'y',
        'ç' | 'ć' | 'č' | 'ĉ' | 'ċ' => 'c',
        'ñ' | 'ń' | 'ň' => 'n',
        'ś' | 'š' | 'ş' | 'ș' => 's',
        'ž' | 'ź' | 'ż' => 'z',
        'ď' | 'đ' => 'd',
        'ť' | 'ț' => 't',
        'ł' => 'l',
        'ř' | 'ŕ' => 'r',
        'ĵ' => 'j',
        'ķ' | 'ĸ' => 'k',
        'ļ' => 'l',
        // Uppercase with accent (convert to lowercase)
        'À' | 'Á' | 'Â' | 'Ã' | 'Ä' | 'Å' | 'Ā' | 'Ă' | 'Ą' => 'A',
        'È' | 'É' | 'Ê' | 'Ë' | 'Ē' | 'Ĕ' | 'Ė' | 'Ę' | 'Ě' => 'E',
        'Ì' | 'Í' | 'Î' | 'Ï' | 'Ī' | 'Ĭ' | 'Į' | 'İ' => 'I',
        'Ò' | 'Ó' | 'Ô' | 'Õ' | 'Ö' | 'Ø' | 'Ō' | 'Ŏ' | 'Ő' | 'Œ' => 'O',
        'Ù' | 'Ú' | 'Û' | 'Ü' | 'Ū' | 'Ŭ' | 'Ů' | 'Ų' | 'Ű' => 'U',
        'Ý' | 'Ÿ' | 'Ȳ' => 'Y',
        'Ç' | 'Ć' | 'Č' | 'Ĉ' | 'Ċ' => 'C',
        'Ñ' | 'Ń' | 'Ň' => 'N',
        'Ś' | 'Š' | 'Ş' | 'Ș' => 'S',
        'Ž' | 'Ź' | 'Ż' => 'Z',
        'Ď' | 'Đ' => 'D',
        'Ť' | 'Ț' => 'T',
        'Ł' => 'L',
        'Ř' | 'Ŕ' => 'R',
        'Ĵ' => 'J',
        'Ķ' => 'K',
        'Ļ' => 'L',
        // Return original if not a known diacritic
        _ => c,
    }
}

/// Quote a string for safe use as a bash argument
fn quote_bash_arg(arg: &str) -> String {
    // ALWAYS wrap in single quotes to prevent ANY shell expansion
    // Single quotes don't allow ANY expansion - not variables, not command substitution,
    // not special characters like &, |, ;, >, <, !, *, ?, etc.
    // Escape single quotes: end string, add escaped single, start new string
    format!("'{}'", arg.replace('\'', "'\\''"))
}

/// Convert a step to a bash function name
/// Example: "Given I run the command `ls`" → "step_given_i_run_the_command_ls"
pub fn step_to_func_name(step: &Step) -> String {
    let keyword = step.keyword().to_lowercase();
    let func_text = to_snake_case(step.text());
    format!("step_{}_{}", keyword, func_text)
}

/// Convert a step to a bash call with optional Data Table and DocString exports
/// This generates the export statements for BATS_BDD_TABLE and BATS_BDD_DOCSTRING
/// if the step has associated data, then calls the step function.
fn step_to_bash_call(step: &Step) -> String {
    let mut output = String::new();

    // Always unset previous BATS_BDD vars to prevent state leak between steps
    output.push_str("  unset BATS_BDD_TABLE BATS_BDD_DOCSTRING\n");

    // Export Data Table if present (CSV format)
    if let Some(table) = step.data_table() {
        let csv = table_to_csv(table);
        output.push_str(&format!("  export BATS_BDD_TABLE='{}'\n", csv));
    }

    // Export DocString if present
    if let Some(doc) = step.doc_string() {
        // Escape single quotes for bash
        let escaped = doc.content.replace('\'', "'\\''");
        output.push_str(&format!("  export BATS_BDD_DOCSTRING='{}'\n", escaped));
    }

    // Call the step function
    let func_name = step_to_func_name(step);
    output.push_str(&format!("  {}\n", func_name));

    output
}

/// Convert a Table to CSV string (for BATS_BDD_TABLE)
fn table_to_csv(table: &crate::parser::ast::Table) -> String {
    let mut csv = String::new();
    for (row_idx, row) in table.rows.iter().enumerate() {
        if row_idx > 0 {
            csv.push('\n');
        }
        for (col_idx, cell) in row.iter().enumerate() {
            if col_idx > 0 {
                csv.push(',');
            }
            // Escape single quotes, double quotes, and wrap in double quotes for proper CSV
            let escaped = cell.replace('"', "\"\"").replace('\'', "'\\''");
            csv.push('"');
            csv.push_str(&escaped);
            csv.push('"');
        }
    }
    csv
}

/// Convert a step to a bash call with args (for Scenario Outline)
/// Handles placeholders, Data Tables, and DocStrings
fn step_to_bash_call_with_args(
    step: &Step,
    headers: &[String],
    row: &[String],
) -> Result<String, CompileError> {
    let mut output = String::new();

    // Always unset previous BATS_BDD vars to prevent state leak between steps
    output.push_str("  unset BATS_BDD_TABLE BATS_BDD_DOCSTRING\n");

    // Export Data Table if present (CSV format)
    if let Some(table) = step.data_table() {
        let csv = table_to_csv(table);
        output.push_str(&format!("  export BATS_BDD_TABLE='{}'\n", csv));
    }

    // Export DocString if present
    if let Some(doc) = step.doc_string() {
        let escaped = doc.content.replace('\'', "'\\''");
        output.push_str(&format!("  export BATS_BDD_DOCSTRING='{}'\n", escaped));
    }

    // Get function name and args from step_to_func_call
    let (func_name, args) = step_to_func_call(step, headers, row)?;
    let call = if args.is_empty() {
        func_name
    } else {
        format!("{} {}", func_name, args.join(" "))
    };
    output.push_str(&format!("  {}\n", call));

    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_step_to_func_name_simple() {
        let step = Step::Given("I have a calculator".to_string(), None, None);
        assert_eq!(step_to_func_name(&step), "step_given_i_have_a_calculator");
    }

    #[test]
    fn test_step_to_func_name_with_backticks() {
        let step = Step::Given("I run the command `ls`".to_string(), None, None);
        assert_eq!(
            step_to_func_name(&step),
            "step_given_i_run_the_command__ls_"
        );
    }

    #[test]
    fn test_step_to_func_name_with_quotes() {
        let step = Step::Then("the result should be \"5\"".to_string(), None, None);
        assert_eq!(
            step_to_func_name(&step),
            "step_then_the_result_should_be__5_"
        );
    }

    #[test]
    fn test_extract_placeholders() {
        let text = "I add <a> and <b>";
        let placeholders = extract_placeholders(text);
        assert_eq!(
            placeholders,
            vec![
                ("<a>".to_string(), "a".to_string()),
                ("<b>".to_string(), "b".to_string())
            ]
        );
    }

    #[test]
    fn test_extract_placeholders_none() {
        let text = "I have a calculator";
        let placeholders = extract_placeholders(text);
        assert!(placeholders.is_empty());
    }

    #[test]
    fn test_step_to_func_call_with_placeholders() {
        let step = Step::When("I add <a> and <b>".to_string(), None, None);
        let headers = vec!["a".to_string(), "b".to_string()];
        let row = vec!["1".to_string(), "2".to_string()];
        let (func_name, args) = step_to_func_call(&step, &headers, &row).unwrap();
        assert_eq!(func_name, "step_when_i_add_a_and_b");
        assert_eq!(args, vec!["'1'", "'2'"]);
    }

    #[test]
    fn test_step_to_func_call_no_placeholders() {
        let step = Step::Given("I have a calculator".to_string(), None, None);
        let headers: Vec<String> = vec![];
        let row: Vec<String> = vec![];
        let (func_name, args) = step_to_func_call(&step, &headers, &row).unwrap();
        assert_eq!(func_name, "step_given_i_have_a_calculator");
        assert!(args.is_empty());
    }

    #[test]
    fn test_step_to_func_call_quoted_args() {
        let step = Step::Given("I have the string <input>".to_string(), None, None);
        let headers = vec!["input".to_string()];
        let row = vec!["hello world".to_string()];
        let (func_name, args) = step_to_func_call(&step, &headers, &row).unwrap();
        assert_eq!(func_name, "step_given_i_have_the_string_input");
        // Single quotes prevent shell expansion
        assert_eq!(args, vec!["'hello world'"]);
    }

    #[test]
    fn test_step_to_func_call_placeholder_not_found() {
        let step = Step::When("I add <banana>".to_string(), None, None);
        let headers = vec!["a".to_string(), "b".to_string()];
        let row = vec!["1".to_string(), "2".to_string()];
        let result = step_to_func_call(&step, &headers, &row);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(matches!(err, CompileError::PlaceholderNotFound(_)));
        assert_eq!(
            err.to_string(),
            "Placeholder 'banana' not found in examples table"
        );
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("Hello World"), "hello_world");
        assert_eq!(to_snake_case("Test 123"), "test_123");
        assert_eq!(to_snake_case("Special!@#Chars"), "special___chars");
    }

    #[test]
    fn test_to_snake_case_with_accents() {
        // Bug B: Portuguese accented characters should be handled
        assert_eq!(
            to_snake_case("Dado que tenho um cenário"),
            "dado_que_tenho_um_cenario"
        );
        assert_eq!(to_snake_case("Olá mundo"), "ola_mundo");
        assert_eq!(to_snake_case("João és tão fã"), "joao_es_tao_fa");
        assert_eq!(to_snake_case("ação"), "acao");
    }

    #[test]
    fn test_extract_placeholders_strict() {
        // Bug C: Only valid identifiers should be extracted
        // Valid placeholders
        let text1 = "I add <a> and <b>";
        let placeholders1 = extract_placeholders(text1);
        assert_eq!(placeholders1.len(), 2);

        // Invalid: < 10 > should NOT be extracted (contains spaces)
        let text2 = "When I check if result is < 10 > 5";
        let placeholders2 = extract_placeholders(text2);
        assert!(
            placeholders2.is_empty(),
            "Should not extract '< 10 >' as placeholder"
        );

        // Invalid: <foo bar> should NOT be extracted (contains space)
        let text3 = "Given I have <foo bar> items";
        let placeholders3 = extract_placeholders(text3);
        assert!(
            placeholders3.is_empty(),
            "Should not extract '<foo bar>' as placeholder"
        );

        // Valid: <foo_bar> with underscore should work
        let text4 = "Given I use <foo_bar>";
        let placeholders4 = extract_placeholders(text4);
        assert_eq!(placeholders4.len(), 1);
        assert_eq!(placeholders4[0].1, "foo_bar");

        // Valid: <123> numeric identifier should work
        let text5 = "Given value is <123>";
        let placeholders5 = extract_placeholders(text5);
        assert_eq!(placeholders5.len(), 1);
        assert_eq!(placeholders5[0].1, "123");
    }

    #[test]
    fn test_quote_bash_arg() {
        // ALL arguments are ALWAYS wrapped in single quotes for security
        // This prevents command injection via special characters like &, |, ;, etc.
        assert_eq!(quote_bash_arg("simple"), "'simple'");
        // Strings with special chars use single quotes (no shell expansion)
        assert_eq!(quote_bash_arg("hello world"), "'hello world'");
        // Double quotes inside single quotes are literal
        assert_eq!(quote_bash_arg("test\"quote"), "'test\"quote'");
        // Single quotes must be escaped
        assert_eq!(quote_bash_arg("test'quote"), "'test'\\''quote'");
        // Malicious input like command substitution should be safely quoted
        assert_eq!(quote_bash_arg("$(whoami)"), "'$(whoami)'");
        assert_eq!(quote_bash_arg("`whoami`"), "'`whoami`'");
        // Command injection via & or | should be safely quoted
        assert_eq!(quote_bash_arg("valor&rm -rf /"), "'valor&rm -rf /'");
        assert_eq!(quote_bash_arg("valor|comando"), "'valor|comando'");
    }
}
