#!/usr/bin/env bats
# Auto-generated by BATS-BDD from: calculator.feature

load 'step_definitions.bash'

setup() {
  step_given_i_have_a_calculator
}

@test "Add two numbers" {
  step_when_i_add_2_and_3
  step_then_the_result_should_be_5
}

@test "Subtract two numbers" {
  step_when_i_subtract_5_from_10
  step_then_the_result_should_be_5
}

@test "Multiply two numbers" {
  step_when_i_multiply_3_and_4
  step_then_the_result_should_be_12
}

