#!/usr/bin/env bats
# Auto-generated by BATS-BDD from: background_steps.feature

load 'step_definitions.bash'

setup() {
  step_given_i_initialize_the_test_environment
  step_and_i_set_the_default_timeout_to_30_seconds
}

@test "First scenario uses background" {
  step_when_i_run_the_first_test
  step_then_the_background_should_be_executed
}

@test "Second scenario also uses background" {
  step_when_i_run_the_second_test
  step_then_the_background_should_be_executed_again
}

@test "Third scenario verifies isolation" {
  step_given_i_verify_the_state_is_clean
  step_when_i_run_the_third_test
  step_then_each_scenario_should_have_fresh_background
}

