#!/usr/bin/env bats
# Auto-generated by BATS-BDD from: simple_scenario_outline.feature

load 'step_definitions.bash'

@test "Add numbers [Example 1]" {
  step_when_i_add_a_and_b 1 2
  step_then_the_result_should_be_sum 3
}
@test "Add numbers [Example 2]" {
  step_when_i_add_a_and_b 3 4
  step_then_the_result_should_be_sum 7
}
@test "Add numbers [Example 3]" {
  step_when_i_add_a_and_b 5 6
  step_then_the_result_should_be_sum 11
}

